version: '3'

services:
  app:
    image: "openjdk:11-jdk"
    working_dir: "/app"
    entrypoint:
      - "./gradlew"
      - "test"
    volumes:
      - $HOME/.gradle:/root/.gradle
      - .:/app
    ports:
      - 8080:8080